### ISSUE TITLE
relationship uuid generation

### ISSUE THREAD

**Issue by ahuwaa** [graphaware/neo4j-uuid#14]
this is great for generating nodes for uuids, but is there a way to also generate uuids for relationships?

**Comment by bachmanm** [comment]
there isn't currently, but it should be a trivial addition - do you wanna have a go and issue a PR? :)

**Comment by Joshfindit** [comment]
If you point the way, I'll have a go.

Also on the table: sane defaults for when UUID is added to a relationship (default: always?)

**Comment by rmarlow** [comment]
I'll second this issue, UUIDs on relationships would be great. No promises, but I'll look into issuing a PR if I get the chance.

**Comment by mikeytag** [comment]
I'll third this issue. It's unfortunate that relationship properties aren't indexed in Neo4j so it has limited use, but if they ever do allow indexing on relationship properties we'll be immediately ready to go with our UUIDs!

**Comment by bachmanm** [comment]
Ok guys, this is gonna get built very soon!

**Comment by mikeytag** [comment]
w00t!

**Comment by bachmanm** [comment]
released in 2.3.2.37.8

**Comment by Joshfindit** [comment]
Bravo!
Thank you!

**Comment by ikwattro** [comment]
For those wondering what the fqdn is for assigning a uuid to all relationships, here it is : 

`com.graphaware.common.policy.all.IncludeAllRelationships`

**Comment by bachmanm** [comment]
or `com.graphaware.module.UIDM.relationship=com.graphaware.runtime.policy.all.IncludeAllBusinessRelationships`

The difference is that if GraphAware Framework is writing some "hidden" relationships, perhaps because you are using another module, these are excluded by the policy above. But if UUID is your only module, then they have the same effect. Actually @ikwattro's suggestion will perform slightly better.
