### ISSUE TITLE
Request for documentation: 0 to neo4j-uuid in Docker

### ISSUE THREAD

**Issue by Joshfindit** [graphaware/neo4j-uuid#17]
A simple quick list of commands/config would be helpful.
Starting from assuming Docker is installed and working, and ending with a running install that generates uuids as per defaults.

**Comment by ikwattro** [comment]
@Joshfindit would a docker-compose setup suit your needs? (I'm generally using docker-compose rather than plain docker commands)

**Comment by Joshfindit** [comment]
Yes, that would be just fine

**Comment by Analect** [comment]
@ikwattro 
Was wondering if you might be able to share the `docker-compose` discussed above (assuming it is available) ... and whether `docker-compose` examples might be available for some of the other related graphaware projects ... like [neo4j-to-elasticsearch](https://github.com/graphaware/neo4j-to-elasticsearch) and [graph-aided-search](https://github.com/graphaware/graph-aided-search). I wasn't able to find anything docker-related on those repos, as yet. Thanks very much.

**Comment by ikwattro** [comment]
@Analect @Joshfindit There is the graph-aided-search-demo repository.

The idea for all plugins is the same. The only difference for graph aided search is the docker network setup (explained in the readme) because it needs bidrectional network between neo4j and es.

https://github.com/graphaware/graph-aided-search-demo

**Comment by Analect** [comment]
@ikwattro Missed this, so thanks for pointing it out.
